version: '3.7'

services:
        php:
                build: './php/'
                networks: 
                        - backend
                volumes: 
                        - type: volume
                          source: public_html
                          target: ${WEB_DESTINATION_PATH}
                environment:
                        - DB_NAME=${DB_NAME}
                        - DB_USER=${DB_USER}
                        - DB_PASSWORD=${DB_PASSWORD}
                        - DB_HOST=${DB_HOST}

        apache: 
                build: './apache/'
                depends_on: 
                        - php 
                        - mysqldb
                networks: 
                        - frontend
                        - backend
                ports: 
                        - "80:80"
                volumes: 
                        - type: volume
                          source: public_html
                          target: ${WEB_DESTINATION_PATH}
 

        mysqldb: 
                build: './mysqldb/'
                volumes:
                        - type: volume
                          source: db_data
                          target: ${DB_DESTINATION_PATH}


                networks: 
                        - backend
                environment:
                        - MYSQL_DATABASE=${DB_NAME}
                        - MYSQL_USER=${DB_USER}
                        - MYSQL_PASSWORD=${DB_PASSWORD}
                        - MYSQL_ROOT_PASSWORD=${DB_RT_PASSWORD}
volumes: 
        public_html:
                driver: local
                driver_opts:
                        type: none 
                        device: ${WEB_APP_PATH}
                        o: 'bind'
        db_data: 
                driver: local
                driver_opts:
                        type: none
                        device: ${DB_PATH}
                        o: 'bind'
networks: 
       frontend:
               driver: bridge
       backend:
               driver: bridge
               
