version: '3.7'

services:
        php:
                build: './php/'
                networks: 
                        - backend
                volumes: 
                        - type: volume
                          source: public_html
                          target: ${WEB_DESTINATION_PATH}
        apache: 
                build: './apache/'
                depends_on: 
                        - php 
                        - mariadb
                networks: 
                        - frontend
                        - backend
                ports: 
                        - "80:80"
                volumes: 
                        - type: volume
                          source: public_html
                          target: ${WEB_DESTINATION_PATH}  

        mariadb: 
                image: hypriot/rpi-mysql
                networks: 
                        - backend
                environment:
                        - MYSQL_DATABASE=wordpress
                        - MYSQL_USER=user
                        - MYSQL_PASSWORD=password
                        - MYSQL_ROOT_PASSWORD=rootpassword
volumes: 
        public_html:
                driver: local
                driver_opts:
                        type: none 
                        device: ./public_html
                        o: 'bind'
networks: 
       frontend:
               driver: bridge
       backend:
               driver: bridge
               
